### PR TITLE
Minor typo

### PR DESCRIPTION
**Pull request by keblek**

### CODE REVIEW

**Comment by Gridflare** [comment]
Sorry, I do actually mean "Farness" here. Farness centrality is the reciprocal of closeness centrality.

I am open to coming up with different text for that line, "modified farness score" doesn't really get across what it should.

**Comment by keblek** [comment]
oh no its my bad, I didn't realize it and though it was something else but now I see what you mean. 

its a change in the distance to the centrality of the node right? or does it mean something else?

**Comment by Gridflare** [comment]
The heuristic used by my algorithm combines a potential peer's farness centrality with the change in farness centrality your node would experience if a channel was opened. I say "modified" to reflect that I'm not using the value directly. Experimentally, this heuristic correlates well with an improvement in betweenness centrality.

**Comment by keblek** [comment]
thanks for the clarification

**Pull request closed without merging**
