### PR TITLE
Convenience printing to file

### PR DESCRIPTION
**Pull request by keblek**
Lets the user easily run bos after running this script to batch open to the various centrality improving nodes.

Suggestions for further improvement
- allow user to put in an xpub or utxo and have this script a come up with a way to fully spend down the utxo amongst the various pub keys so that there is no change output (this can improve privacy and make node management more straightforward)

### CODE REVIEW

**Comment by Gridflare** [comment]
This is a neat idea, but this script returns 20+ pubkeys, that's a lot of channels to open in a single batch. You can configure the script to return fewer results, but the accuracy suffers. The experience of myself and others with these results is that blindly improving your centrality does not equate to improved routing.

The script already outputs a CSV, it may be better to write a new script that imports this CSV, double checks node candidates, and handles the channel size calculations, before passing to bos. If this new script was able to present stats and interactively guide the user through narrowing down the pubkey list, that would be really cool.

An aside: Using a single-utxo to fully fund a channel improves privacy, but batch opens effectively reveal the channel initiator, so I think that cancels out.

**Comment by keblek** [comment]
I am not suggesting that people auto manage their node, that is a good way to not be very effective. 

With regards to the size, you can use head or tail in the CLI to chop it down. I think 3-5 peers to batch with is a good size, otherwise you get connection issues and the whole process gets ruined by one peer.

Yes I agree that some interactive (G)UI would be quite useful here (that shows metrics and stats and can do on the fly calculations to see how the graph changes). Have you ever used Jupiter notebooks?  I think that would be a good compromise for an interface. 

I actually see that you can configure to print out to CSV via pandas. I think this is simpler.

Maybe as a compromise, I think we can add a short shell command to process that csv file and turn it into something BOS can use in the README? This way people can use it now while that other script gets developed.

I figured since this is LND based that most people using this tool would also use BOS. 

Batching helps to avoid change output which is very hard to spend privately.  I understand there are tradeoffs but its good to do in certain situations (if you just have one big UTXO and want to start a routing node). Also in the future we will (hopefully) have dual funded channels which I believe should render that heuristic (channel initiator based on batching) much less useful.

**Comment by keblek** [comment]
One question, to get the advertised change in centrality, would a user need to open channels with all the pubkeys listed in the script?

**Comment by Gridflare** [comment]
> With regards to the size, you can use head or tail in the CLI to chop it down. I think 3-5 peers to batch with is a good size, otherwise you get connection issues and the whole process gets ruined by one peer.

Blindly chopping is not a good strategy, the user needs to do some sort of filtering. The automatic filtering is already pretty good, the room for improvement is aiding in manual filtering.

> Have you ever used Jupiter notebooks? I think that would be a good compromise for an interface.

I do my heuristic testing in Jupyter, I don't see how it could be made into a nice user-friendly interface, though.

> Maybe as a compromise, I think we can add a short shell command to process that csv file and turn it into something BOS can use in the README? This way people can use it now while that other script gets developed.

We could add a folder that contains small scripts for transforming output. But if the user has to specify the desired channel size for each peer, I don't see how this improves over copy and pasting the pubkeys.

> One question, to get the advertised change in centrality, would a user need to open channels with all the pubkeys listed in the script?

No. This is another issue with the proposed approach that I forgot to mention earlier. The script assumes you will only open to 1 of the results. If you  want to open to more than 1 there are lists near the top of the file for adding pubkeys one-by-one.

Automatically computing an optimal batch open, optimizing channel size, peer quality, and centrality boost is an extremely difficult problem and the script is already computationally intense.

**Comment by Gridflare** [comment]
LND will be adding support for batch opens as well. I favour the accessory script option for ease of providing compatiblity with both bos and lncli.

**Comment by keblek** [comment]
> I do my heuristic testing in Jupyter, I don't see how it could be made into a nice user-friendly interface, though.

I think Jupyter is a step above text editors, it's a compromise since I think adding a graphical user interface to something like this would be very challenging.

> We could add a folder that contains small scripts for transforming output. But if the user has to specify the desired channel size for each peer, I don't see how this improves over copy and pasting the pubkeys.

I think anything to help aid and make it more convenient is worth it. Although I agree it's not that much more beneficial.

Have you ever tried Justfiles? It's like a makefile (we can use those too) but with simpler syntax. Downside is you have to install it but its quite nice. I think we can put the helper commands in there and keep them in one file. 

There are a few convenience commands I can add I think LN node operators will like.

> This is another issue with the proposed approach that I forgot to mention earlier. The script assumes you will only open to 1 of the results. If you want to open to more than 1 there are lists near the top of the file for adding pubkeys one-by-one.

That's good to know. Thanks.

> Automatically computing an optimal batch open, optimizing channel size, peer quality, and centrality boost is an extremely difficult problem and the script is already computationally intense.

Indeed it is, thank you for making this script and for sharing it. I (and I'm sure many others) appreciate it. 

Yea that's true but it's not ran often. If I have to run the script every once in a while and get coffee while I wait then I personally wouldn't mind. Although I get what you mean.  

> LND will be adding support for batch opens as well

Yes I saw this, long requested feature.

**Comment by Gridflare** [comment]
> I think Jupyter is a step above text editors, it's a compromise since I think adding a graphical user interface to something like this would be very challenging.

A graphical interface is out of scope for this repo. It is better to put energy into a website.

> Have you ever tried Justfiles? It's like a makefile (we can use those too) but with simpler syntax. Downside is you have to install it but its quite nice. I think we can put the helper commands in there and keep them in one file.
There are a few convenience commands I can add I think LN node operators will like.

I'm not familiar. There are a few lists of handy command line aliases floating around, if you want to assemble those into a justfile I think that would be better suited to a new repo.

> Yea that's true but it's not ran often. If I have to run the script every once in a while and get coffee while I wait then I personally wouldn't mind. Although I get what you mean.

I've been thinking about it, and I have an idea for a heuristic that would probably only double the runtime. I'll put it on my research backlog.


If you'd like to add your bos support to this repo, I suggest writing a short script that takes in improvecentrality.csv and desired channel size(s). It can be placed in a folder titled `accessory` that more stuff can be added to over time.
A catch to watch out for is that most people do not run improvecentrality on node hardware, so it would need to support `bos --node` for remote connection.

**Pull request closed without merging**
